" __   _(_)_ __ ___  _ __ ___
" \ \ / / | '_ ` _ \| '__/ __|
"  \ V /| | | | | | | | | (__
"   \_/ |_|_| |_| |_|_|  \___|
"
" Eric Iacutone's vimrc

set modelines=1
set shell=zsh
syntax enable

" Recursive searching into sub dirs
set path+=**

" Display matching files on tab complete
set wildmenu

" Create ctags
command! MakeTags !ctags -R .
" nnoremap <leader>ct :silent !ctags -R --languages=ruby --exclude=.git --exclude=log . $(bundle list --paths)

" Yank to OSX clipboard
set clipboard=unnamed

" highlight current line
set cursorline

set incsearch " search as characters are entered
set hlsearch  " highlight matches

set mouse=a " scroll within tmux

" turn off search highlight
nnoremap <leader><space> :nohlsearch<CR>

" Easier window management
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" Next buffer
nnoremap <Tab> :bnext<cr>

set foldmethod=marker
set foldlevel=0
" vim-plug {{{
call plug#begin()
" Colors and styles
Plug 'airblade/vim-gitgutter'
Plug 'altercation/vim-colors-solarized'
Plug 'ap/vim-css-color'
Plug 'itchyny/lightline.vim'
Plug 'luochen1990/rainbow'
Plug 'mhinz/vim-startify'

" Productivity
Plug 'janko-m/vim-test'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'mileszs/ack.vim'
Plug 'mtth/scratch.vim'
Plug 'ojroques/vim-oscyank', {'branch': 'main'}
Plug 'pbrisbin/vim-mkdir'
Plug 'Raimondi/delimitMate'
Plug 'rhysd/devdocs.vim'
Plug 'rizzatti/dash.vim'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-rhubarb'
Plug 'tpope/vim-surround'

" Language servers and linters
Plug 'dense-analysis/ale'

" Languages and syntax
Plug 'elixir-editors/vim-elixir'
Plug 'rust-lang/rust.vim'
Plug 'sheerun/vim-polyglot'
call plug#end()
filetype plugin indent on
" }}}

set autoindent

" Only do this part when compiled with support for autocommands
if has("autocmd")
  autocmd FileType ruby,haml,eruby,yaml,html,javascript,sass,css,scss,cucumber,coffee,sh,erl setlocal ai sw=2 sts=2 et
  autocmd FileType elm setlocal sw=4 sts=4 ts=4
  autocmd BufWritePre *.rb,*.js :call <SID>StripTrailingWhitespaces()
endif

function! <SID>StripTrailingWhitespaces()
   " Preparation: save last search, and cursor position.
   let _s=@/
   let l = line(".")
   let c = col(".")
   " Do the business:
   %s/\s\+$//e
   " Clean up: restore previous search history, and cursor position
   let @/=_s
   call cursor(l, c)
endfunction

let mapleader = ','
set background=dark
let g:solarized_termcolors=256
colorscheme solarized
set backspace=indent,eol,start
set encoding=utf-8

nmap <silent> <leader>s :TestNearest<CR>
nmap <silent> <leader>t :TestFile<CR>
nmap <silent> <leader>a :TestSuite<CR>
nmap <silent> <leader>l :TestLast<CR>
nmap <silent> <leader>g :TestVisit<CR>
" let test#strategy = 'vtr'
let test#filename_modifier = ':.'

let g:tagbar_ctags_bin='/usr/local/bin/ctags'
let g:tagbar_width=30
noremap <silent> <Leader>y :TagbarToggle
let b:surround_{char2nr('=')} = "<%= \r %>"
let b:surround_{char2nr('-')} = "<% \r %>"
vmap <Leader>z :call I18nTranslateString()<CR>
vmap <Leader>dt :call I18nDisplayTranslation()<CR>

nmap <silent> <leader>dd <Plug>(devdocs-under-cursor)
nmap <silent> <leader>da <Plug>DashSearch

let g:task_rc_override = 'rc.defaultwidth=0'
nnoremap <F2> :set invpaste paste?<CR>
set pastetoggle=<F2>
set showmode

cnoreabbrev Ack Ack!

" Tell ack.vim to use ag (the Silver Searcher) instead
if executable('ag')
  let g:ackprg = 'ag --vimgrep'
endif

nmap ; :Buffers<CR>
nmap <C-p> :Files<CR>
nmap <Leader>r :Tags<CR>
nmap <M-k> :Ack! "\b<cword>\b" <CR>
set rtp+=/usr/local/opt/fzf
command! Q q

" ALE
let g:ale_sign_warning = '▲'
let g:ale_sign_error = '✗'
let g:ale_fixers = { 'elixir': ['mix_format'], 'typescript': ['prettier', 'eslint'], 'javascript': ['prettier', 'eslint'] }
let g:ale_linters = { 'typescript': [ 'eslint' ], 'javascript': [ 'eslint' ] }
let g:ale_fix_on_save = 1
highlight link ALEWarningSign String
highlight link ALEErrorSign Title

" Lightline {{{
set laststatus=2
set noshowmode
let g:lightline = {
\ 'colorscheme': 'jellybeans',
\ 'active': {
\   'left': [['mode', 'paste'], ['filename', 'modified', 'gitbranch']],
\   'right': [['lineinfo'], ['percent'], ['readonly', 'linter_warnings', 'linter_errors', 'linter_ok']]
\ },
\ 'component_expand': {
\   'linter_warnings': 'LightlineLinterWarnings',
\   'linter_errors': 'LightlineLinterErrors',
\   'linter_ok': 'LightlineLinterOK'
\ },
\ 'component_type': {
\   'readonly': 'error',
\   'linter_warnings': 'warning',
\   'linter_errors': 'error'
\ },
\ 'component_function': {
\   'gitbranch': 'fugitive#head'
\ },
\ }

function! LightlineLinterWarnings() abort
  let l:counts = ale#statusline#Count(bufnr(''))
  let l:all_errors = l:counts.error + l:counts.style_error
  let l:all_non_errors = l:counts.total - l:all_errors
  return l:counts.total == 0 ? '' : printf('%d ◆', all_non_errors)
endfunction

function! LightlineLinterErrors() abort
  let l:counts = ale#statusline#Count(bufnr(''))
  let l:all_errors = l:counts.error + l:counts.style_error
  let l:all_non_errors = l:counts.total - l:all_errors
  return l:counts.total == 0 ? '' : printf('%d ✗', all_errors)
endfunction

function! LightlineLinterOK() abort
  let l:counts = ale#statusline#Count(bufnr(''))
  let l:all_errors = l:counts.error + l:counts.style_error
  let l:all_non_errors = l:counts.total - l:all_errors
  return l:counts.total == 0 ? '✓ ' : ''
endfunction

autocmd User ALELint call s:MaybeUpdateLightline()

" Update and show lightline but only if it's visible (e.g., not in Goyo)
function! s:MaybeUpdateLightline()
  if exists('#lightline')
    call lightline#update()
  end
endfunction
" }}}

" clear highlights by hitting ESC
" or by hitting enter in normal mode
nnoremap <CR> :noh<CR><CR>

" Don't add the comment prefix when I hit enter or o/O on a comment line.
autocmd FileType * setlocal formatoptions-=r formatoptions-=o

inoremap <tab> <c-n><c-p>

" Autocomplete
let g:deoplete#enable_at_startup = 1

vmap <C-c><C-c> <Plug>SendSelectionToTmux
nmap <C-c><C-c> <Plug>NormalModeSendToTmux
nmap <C-c>r <Plug>SetTmuxVars

imap <c-c> <esc>

highlight clear SignColumn

set tags+=tags
let g:ale_fixers = { 'elixir': ['mix_format'] }

vnoremap <leader>c :OSCYank<CR>
nmap <leader>o <Plug>OSCYank

set tags+=tag

" Permanent undo
set undodir=~/.vimdid
set undofile

" No arrow keys --- force yourself to use the home row
nnoremap <up> <nop>
nnoremap <down> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>

" from http://sheerun.net/2014/03/21/how-to-boost-your-vim-productivity/
if executable('ag')
	set grepprg=ag\ --nogroup\ --nocolor
endif
if executable('rg')
	set grepprg=rg\ --no-heading\ --vimgrep
	set grepformat=%f:%l:%c:%m
endif

let g:fzf_layout = { 'down': '~20%' }
command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   'rg --column --line-number --no-heading --color=always '.shellescape(<q-args>), 1,
  \   <bang>0 ? fzf#vim#with_preview('up:60%')
  \           : fzf#vim#with_preview('right:50%:hidden', '?'),
  \   <bang>0)
